<?php

namespace Lazzard\FtpBridge\Tests\Exception;

use Lazzard\FtpBridge\Exception\ResponseParserException;

class ResponseParserExceptionTest extends ExceptionTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->exceptionClass = ResponseParserException::class;
    }
}
