<?php

namespace Lazzard\FtpBridge\Tests\Exception;

use Lazzard\FtpBridge\Exception\StreamException;

class StreamExceptionTest extends ExceptionTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->exceptionClass = StreamException::class;
    }
}
